### PR TITLE
fix alignment of permission title/combobox

### PR DESCRIPTION
**Pull request by fmigneault**
## Changes / Fixes

* Add auto-restore of previous scroll position in UI page following submitted form.
* Add UI tooltip `Resource` ID to elements rendered in the ``Service`` and ``Permission`` hierarchy trees
  (relates to #335).
* Fix UI alignment of permission titles with their corresponding permission selectors
  (relates to #498).

### CODE REVIEW

**Review by dbyrns — COMMENTED** [review]
It's a nice addition to store the scrolling position.
If my understanding is correct the tooltip apply to the ressources, but it would be really usefull for the permission title too when there is an overflow and ellipsis is applied.
I will let @f-PLT makes the final approval after he checks the rendering.

**Comment by f-PLT** [comment]
Code looks good to me, and rendering worked as expected on Firefox and Chrome on my end.

**Review by f-PLT — APPROVED** [review]

**Comment by fmigneault** [comment]
@dbyrns 
> for the permission title too when there is an overflow and ellipsis is applied.

Doesn't it display a scrollbar when the title is too large? That's what it is supposed to do.

**Comment by dbyrns** [comment]
> Doesn't it display a scrollbar when the title is too large? That's what it is supposed to do.

Didn't test it. `text-overflow: ellipsis;` for me is used when `...` replace the text that don't fit it the space. Fine with me if a scrollbar is available and all the permission can be read.

**Review by dbyrns — APPROVED** [review]

**Comment by f-PLT** [comment]
> > Doesn't it display a scrollbar when the title is too large? That's what it is supposed to do.
> 
> Didn't test it. `text-overflow: ellipsis;` for me is used when `...` replace the text that don't fit it the space. Fine with me if a scrollbar is available and all the permission can be read.

I did a quick test with CSS in an editor, the lack of `...` could be related to `  display: inline-flex;` in the `permission-cell` class, as they are applied to the same divs. 

Actually replacing with `...` could make it confusing for people who are not familiar with the operations in question (unless a tooltip or other way to see the full name is available)

Anyway, I think that once a full length horizontal scrollbar is available for permission (as is cited in https://github.com/Ouranosinc/Magpie/issues/498), the columns could also be widened so the full title is visible for all columns.

**Comment by fmigneault** [comment]
merging as is, lint errors resolved in PR #502

**Comment by fmigneault** [comment]
For documentation purpose, the tooltip in question: 

image

**Pull request merged**
