### PR TITLE
[WIP] 0.7.0 preview

### PR DESCRIPTION
**Pull request by davidcaron**
This PR contains #104 #106 and #109

Current status on colibri:
- The cron service works, I based the PAVICS branch on https://github.com/Ouranosinc/PAVICS/pull/99.
- project-api is set to colibri.crim.ca:3005/api but colibri.crim.ca:3005/api/Projects returns a 500

### Waiting for this PR to merge/deploy: https://github.com/Ouranosinc/PAVICS/pull/99

### CODE REVIEW

**Comment by fmigneault** [comment]
`project-api` should now point to `http://colibri.crim.ca:3005/api` to match new `ServiceAPI` functionality.

http://colibri.crim.ca:3005/api/Jobs returns valid responses
see http://colibri.crim.ca:3005/explorer/ for full spec of the api

**Comment by davidcaron** [comment]
I thought it wasn't running, but http://colibri.crim.ca:3005/api/Projects actually returns a 500 error

**Comment by fmigneault** [comment]
500 is internal error, so project-api as an error when executing GET Projects, but service is up otherwise.
@Renaud009 you know about this issue?

**Comment by fmigneault** [comment]
Using latest magpie, I got an error related to new version of gunicorn.
Using following patch resolved the issue: 
https://github.com/Ouranosinc/Magpie/blob/7989367c0a96e51885ea1f074e5bd1053ae1d608/requirements.txt#L24

We should cherry-pick this tweak into 0.7.0 version

**Comment by davidcaron** [comment]
@fmigneault is there a reason `logging` was added in requirements.txt? It got removed by cherry-picking for the gunicorn version.

**Comment by fmigneault** [comment]
Removed as it's not necessary, was getting an error because of pycharm acting up, but no code issue.

**Comment by fmigneault** [comment]
closes #104 #106 and #109

**Pull request merged**
