### PR TITLE
fix email related validation to avoid duplicates

### LINKED ISSUE #521: [BUG] Unable to add any new user
**Describe the bug**

Unable to add any new user.  Before I thought it was "unclear error when adding new user matching an already existing user name" but my collegue @tlogan2000 and @Zeitsperre told me they used new non-existing username and they still get the error:

image

```
[2022-08-31 18:50:02,141] INFO       [ThreadPoolExecutor-0_0][magpie.utils] Request: [POST pavics.ouranos.ca:443 /magpie/users]                          
[2022-08-31 18:50:02,154] ERROR      [ThreadPoolExecutor-0_0][magpie.ui.utils] Unexpected API error under UI operation. [{'code': 409, 'detail': 'User nam
e matches an already existing user name.', 'type': 'application/json', 'path': '/users', 'url': 'https://pavics.ouranos.ca/magpie/users', 'method': 'POST'
}]                                                                                                                                                       
[2022-08-31 18:50:02,154] INFO       [ThreadPoolExecutor-0_0][magpie.utils] Request: [POST pavics.ouranos.ca:443 /magpie/ui/error]                       
[2022-08-31 18:50:02,160] INFO       [ThreadPoolExecutor-0_0][magpie.api.requests] User 'logan' is authenticated                                         
[2022-08-31 18:50:02,161] ERROR      [ThreadPoolExecutor-0_0][magpie.ui.utils] Unexpected API error under UI operation. [TypeError: 'Response' object is n
ot subscriptable]                                                                                                                                        
Traceback (most recent call last):                                                                                                                       
  File "/opt/local/src/magpie/magpie/ui/utils.py", line 150, in wrap                                                                                     
    return func(*args, **kwargs)                                                                                                                         
  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view                                                      
    result = view(context, request)                                                                                                                      
  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view                                            
    response = getattr(inst, attr)()                                                                                                                     
  File "/opt/local/src/magpie/magpie/ui/management/views.py", line 107, in add_user                                                                      
    if return_data["is_error"]:                                                                                                                          
TypeError: 'Response' object is not subscriptable
```

**To Reproduce**
1. Deploy Magpie from this birdhouse-deploy commit https://github.com/Ouranosinc/birdhouse-deploy/commit/2ed45aac7e5442dc56298ca87e036b474f6c6528

**Desktop (please complete the following information):**
 - OS: [e.g. Linux|Windows] (if running locally) from Magpie docker image
 - Browser [e.g. chrome, safari] (if running as a service) 
 - Instance: URL  https://pavics.ouranos.ca/magpie/version
 - Version 3.26.0

### PR DESCRIPTION
**Pull request by fmigneault**
# Features / Changes

* Add database unique index to ensure case-insensitive ``User`` email cannot be stored.
* Display ``User`` email field in UI page providing the list of registered and pending users.
* Add ``mailto:`` link for all ``User`` email fields displayed in UI.

# Bug Fixes
* Fix conflicting ``User`` email not properly reported in UI with an appropriate message in creation page.
  The ``User`` name was instead reported as the conflicting property, although it was not the problematic field 
  (resolves #521).

# Important 
If any ``User`` entries with duplicate case-insensitive emails are present in the database, the application will fail when performing the database migration. Resolve those cases manually before starting `Magpie`.

### CODE REVIEW

**Review by tlvu — APPROVED** [review]
Don't know the code much, approve the spirit of this PR.

**Comment by tlvu** [comment]
@fmigneault 

Question, during DB migration, if it finds duplicate email, will there be message in the logs (`docker logs mapgie`) to let us know which email was causing the problem?  In case did not catch all duplicate email before hand.

@tlogan2000 @Zeitsperre We will need to remove all the duplicate email accounts before upgrading to a version of Magpie containing this PR.

We have to tell users to decide which account they want to keep and transfer their user data from the account we will destroy to the account they want to keep.

**Comment by fmigneault** [comment]
> Question, during DB migration, if it finds duplicate email, will there be message in the logs (`docker logs mapgie`) to let us know which email was causing the problem? In case did not catch all duplicate email before hand.

There should be an SQL message related to the conflict when creating the index.

**Comment by tlvu** [comment]
> @tlvu do you know if there are there other duplicates in the database right now?

@tlogan2000 
Quick inspection, I only saw 2 yesterday that you already delete this morning.

I replicate the production DB to a staging host and test the migration before hand each time I know Magpie has a DB migration.  We will know for sure by then.

**Comment by fmigneault** [comment]
@tlvu Version `3.27.0` is building, the Docker should be ready in a few minutes.

**Pull request merged**
