### PR TITLE
add path to fix import

### PR DESCRIPTION
**Pull request by fmigneault**
resolves issue #27

### CODE REVIEW

**Comment by dbyrns** [comment]
I would prefer if @huard could confirm that this PR solve his issue.

**Comment by fmigneault** [comment]
@huard is the files permission not set locally for you? I don't see where the make install process would change permissions

**Comment by huard** [comment]
Git stores the permissions, so my guess is that the Magpie devs worked on windows, which I believe has different default permissions from linux. 

I just think it's a matter of "chmod"ding the files and commit.

**Comment by fmigneault** [comment]
That's why I'm a bit confused, on my side, it seems they are almost all set to -rwx------, except maybe a few files here and there that are -rwxrwxr-x. I can change all to -rw-rw-r--

**Comment by huard** [comment]
image

**Comment by fmigneault** [comment]
image

**Comment by fmigneault** [comment]
I can at least chown the files for a common user, then try chmod them.

**Pull request merged**
