### PR TITLE
Gunicorn access logs

### PR DESCRIPTION
**Pull request by davidcaron**
This prints the gunicorn access logs to stdout.

I don't know what you think, but I think this helps debugging...

### CODE REVIEW

**Comment by fmigneault** [comment]
@davidcaron 
having quite a lot of trouble figuring out what's failing on travis
everything works fine for local/remote tests on my machine

**Comment by tomLandry** [comment]
Maybe the type of thing @ldperron could help troubleshoot?

**Comment by ldperron** [comment]
Unfortunately, Travis doesn't collect any details about the 500 error. Should we try adding it to Sentry?

**Comment by davidcaron** [comment]
I restarted it and it worked... 

The only thing I see is that when I created the PR, it targeted the master branch, but I quickly changed it to login-local-subreq. Maybe travis picked up something wrong when checking out the PR.

**Pull request merged**
