### PR TITLE
Fix 500 on current user services

### PR DESCRIPTION
**Pull request by davidcaron**

### CODE REVIEW

**Comment by davidcaron** [comment]
fixes https://github.com/Ouranosinc/PAVICS-DataCatalog/issues/50

**Comment by huard** [comment]
@tlvu If the catalog_search notebook runs with this, we're good.

**Comment by davidcaron** [comment]
> 
> 
> @tlvu If the catalog_search notebook runs with this, we're good.

Good to know, I'll test this one.

**Comment by tlvu** [comment]
In case you want to do a real Jenkins test:
* deploy a new Magpie containing this fix
* request a build on Jenkins pointing to the server with this Magpie fix

**Pull request merged**
