### PR TITLE
PAV-416 Standardize HTTP error codes

### PR DESCRIPTION
**Pull request by fmigneault**
## principal changes

- adds `api_except` for multiple utility functions that standardize http responses according to status and other provided json content
- adds `api_requests` that provides utility 'get from POST/PATH/QUERY' validation functions
- change version to `0.2.0` - major revamp of returned http codes / values
- API docs 
    * swaggerhub still points automatically to 'default' [0.1.1](https://app.swaggerhub.com/apis/fderue/magpie-rest_api/0.1.1)
    * [WIP] [0.2.0](https://app.swaggerhub.com/apis/fderue/magpie-rest_api/0.2.0) under construction 
    * will change 'default' for 0.2.0 when completed & merged
    * [TODO] update confluence links to 'default' swaggerhub API 

## included changes

- quick fix of `python-openid` dependency
- multiple warnings fixes, unicode text problems

### Good Response - Standardized [magpie/users] => Returns `HTTPOk`
```json
{
    "code": 200,
    "type": "application/json",
    "detail": "Get users successful",
    "user_names": [
        "anonymous", 
        "admin", 
        "david", 
        "felix", 
        "fderue_openid", 
        "francis"]
}
```

### Good Response - Old [magpie/users] => Returns `HTTPOk`
```json
{
    "user_names": [
        "anonymous", 
        "admin", 
        "david", 
        "felix", 
        "fderue_openid", 
        "francis"]
}
```

### Bad Response - Standardized [magpie/users/*NOT_USER*/resources] => Returns `HTTPNotFound`
```json
{
    "code": 404,
    "type": "application/json",
    "detail": "User name not found in db",
    "param": "NOT_USER"
}
```
### Bad Response - Old [magpie/users/*NOT_USER*/resources] => Returns `HTTPBadRequest` 
(**_HTML / code in string header + wrong HTTP code!_**)
```html
<html>
 <head>
  <title>400 Bad Request</title>
 </head>
 <body>
  <h1>400 Bad Request</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
This user does not exist
 </body>
</html>
```

And `HTTPInternalServerError` (500) is properly returned instead of `HTTPBadRequest` (400) when the errors is caused by programming problems like accessing a non-existing `dict` key.

### CODE REVIEW

**Comment by dbyrns** [comment]
:+1:

**Comment by fderue** [comment]
super, j'ai juste remarqué que lorsque tu rajoutes un groupe vide, la gestion du code d'erreur n'est pas la même, je pense que c'est toujours sur l'ancienne version. En plus ça reste bloqué en Bad request à chaque fois que l'on revient sur l'onglet "groupe"

**Comment by fmigneault** [comment]
@fderue 
Group value check for empty `u''` is not accomplished and properly refused by API.
BadRequest is caused by that group added during testing, ie:  a dict creation with key `u''` is attempted, and is obviously refused.

Temporarily, I put a check to leave out the empty group names, but there is currently an actual `u''`  group in the postgres DB. Any ideas how to remove it on remote?

**Comment by fmigneault** [comment]
@dbyrns login is now fixed, redirects to home

**Pull request merged**
